trainer:
  logger: true
  max_epochs: 1000
  num_sanity_val_steps: 2
  gradient_clip_val: 10000.0
  gradient_clip_algorithm: norm
  accelerator: auto
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_avg_loss
        patience: 30
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_avg_loss
        mode: min
        save_top_k: 1
        dirpath: ../results/lightning_model_checkpoints/MML
        filename: MML_shr_scn3D

model:
  class_path: AdaptiveHeatmapRegression
  init_args:
    model:
      class_path: landmarker.models.OriginalSpatialConfigurationNet3d
      init_args:
        in_channels: 1
        out_channels: 14
    heatmap_generator:
      class_path: landmarker.heatmap.GaussianHeatmapGenerator
      init_args:
        nb_landmarks: 14
        heatmap_size: [128, 128, 64]
        sigmas: 5.0
        gamma: 1000.0
        learnable: True
    loss:
      class_path: landmarker.losses.GaussianHeatmapL2Loss
      init_args:
        alpha: 5
    decoder_method: local_soft_argmax
    lr: 1e-6
    final_activation:
      class_path: torch.nn.ReLU
    spatial_dims: 3

data:
  class_path: MLLLightningDataModule
  init_args:
    data_dir: ../data
    kind: heatmap
    batch_size: 1
    num_workers: 7
    dim_img: [128, 128, 64]
    train_transform:
      class_path: monai.transforms.Compose
      init_args:
        transforms:
          - class_path: monai.transforms.RandAffined
            init_args:
              keys: [image]
              prob: 1.0
              rotate_range: [0.3, 0.3, 0.2]
              translate_range: [10, 10, 10]
              scale_range: [0.1, 0.1, 0.05]
          - class_path: monai.transforms.ScaleIntensityd
            init_args:
              keys: [image]
              dtype: null
    inference_transform:
      class_path: monai.transforms.Compose
      init_args:
        transforms:
          - class_path: monai.transforms.ScaleIntensityd
            init_args:
              keys: [image]
              dtype: null

          

