trainer:
  logger: true
  max_epochs: 1000
  num_sanity_val_steps: 2
  gradient_clip_val: 10000.0
  gradient_clip_algorithm: norm
  accelerator: auto
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: val_avg_loss
        patience: 30
        mode: min
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_avg_loss
        mode: min
        save_top_k: 1
        dirpath: ../results/lightning_model_checkpoints/MML
        filename: MML_shr_scn3D

model:
  class_path: StaticHeatmapRegression
  init_args:
    model:
      class_path: monai.networks.nets.FlexibleUNet
      init_args:
        in_channels: 1
        out_channels: 14
        backbone: efficientnet-b0
        spatial_dims: 3
        pretrained: True
        norm: batch
        act: relu
    loss:
      class_path: landmarker.losses.NLLLoss
      init_args:
        spatial_dims: 3
    final_activation:
      class_path: landmarker.models.utils.SoftmaxND
      init_args:
        spatial_dims: 3
    spatial_dims: 3
    decoder_method: argmax
    lr: 1e-3

data:
  class_path: MLLLightningDataModule
  init_args:
    data_dir: ../data
    kind: mask
    batch_size: 8
    num_workers: 5
    dim_img: [128, 128, 64]
    train_transform:
      class_path: monai.transforms.Compose
      init_args:
        transforms:
          - class_path: landmarker.transforms.images.UseOnlyFirstChannel
            init_args:
              keys: [image]
          - class_path: monai.transforms.ScaleIntensityd
            init_args:
              keys: [image]
              dtype: null
    inference_transform:
      class_path: monai.transforms.Compose
      init_args:
        transforms:
          - class_path: landmarker.transforms.images.UseOnlyFirstChannel
            init_args:
              keys: [image]
          - class_path: monai.transforms.ScaleIntensityd
            init_args:
              keys: [image]
              dtype: null

